# Cocioran Stefan 321CA

CFLAGS = g++ -std=c++11 -g -Werror -Wall

all: server tcp_client udp_sender

# Compileaza server.cpp
server: server.cpp

# Compileaza tcp_client.cpp
tcp_client: tcp_client.cpp

# Compileaza udp_sender.cpp
udp_sender: udp_sender.cpp

clean:
	rm -f server tcp_client udp_sender
